In [1]:
import pandas as pd
import numpy as np
import re

# In[ ]:
df0 = pd.read_excel("Energy Indicators.xls") #use r before absolute file path 
df = df0[17:244]
#print(df.head())
del df['Unnamed: 0']
del df['Unnamed: 1']
df.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
#x = pd.ExcelFile('Energy Indicators.xls')
#energy = x.parse(skiprows=17,skip_footer=(38))
#print(energy])
#energy = energy[[1,3,4,5]]
#energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy = df
energy[['Energy Supply', 'Energy Supply per Capita', '% Renewable']] =  energy[['Energy Supply', 'Energy Supply per Capita', '% Renewable']].replace('...',np.NaN).apply(pd.to_numeric)
energy['Energy Supply'] = 1000000*energy['Energy Supply']
energy['Country'] = energy['Country'].apply(lambda x: re.findall('([^0-9]*)',x)[0].strip())
energy['Country'] = energy['Country'].apply(lambda x: re.findall('([^\(]*)',x)[0].strip())
energy['Country'] = energy['Country'].replace({'China, Hong Kong Special Administrative Region':'Hong Kong','United Kingdom of Great Britain and Northern Ireland':'United Kingdom','Republic of Korea':'South Korea','United States of America':'United States','Iran (Islamic Republic of)':'Iran'})
energy['Country'] = energy['Country'].str.replace(r" \(.*\)","")

GDP = pd.read_csv('world_bank.csv',skiprows=4)
GDP['Country Name'] = GDP['Country Name'].replace({'Korea, Rep.':'South Korea','Iran, Islamic Rep.':'Iran','Hong Kong SAR, China':'Hong Kong'})
GDP = GDP[['Country Name','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']]
GDP.columns = ['Country','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']

ScimEn = pd.read_excel(io='scimagojr-3.xlsx')
ScimEn = ScimEn[:15]
df = pd.merge(ScimEn,energy,how='inner',left_on='Country',right_on='Country')
new_df = pd.merge(df,GDP,how='inner',left_on='Country',right_on='Country')
new_df = new_df.set_index('Country')

new_df

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
<ipython-input-1-b45d246ded48>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  energy['Energy Supply'] = 1000000*energy['Energy Supply']
<ipython-input-1-b45d246ded48>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  energy['Country'] = energy['Country'].apply(lambda x: re.findall('([^0-9]*)',x)[0].strip())
<ipython-input-1-b45d246ded48>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  energy['Country'] = energy['Country'].apply(lambda x: re.findall('([^\(]*)',x)[0].strip())
<ipython-input-1-b45d246ded48>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  energy['Country'] = energy['Country'].replace({'China, Hong Kong Special Administrative Region':'Hong Kong','United Kingdom of Great Britain and Northern Ireland':'United Kingdom','Republic of Korea':'South Korea','United States of America':'United States','Iran (Islamic Republic of)':'Iran'})
<ipython-input-1-b45d246ded48>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  energy['Country'] = energy['Country'].str.replace(r" \(.*\)","")

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [3]:
Top15 = new_df
m = Top15.iloc[:,8].mean()
print(m)
mx = Top15.iloc[:,9].max()
print('Brazil',mx)

Top15['Ratio'] = Top15.iloc[:,4]/Top15.iloc[:,3]
('China',Top15.iloc[:,20].max())

157.6
Brazil 69.64803

('China', 0.6893126179389422)

In [4]:
Top15['Pop'] = Top15.iloc[:,7]/Top15.iloc[:,8]
Top15['Citable docs per Capita'] = Top15.iloc[:,2]/Top15['Pop']
Top15[['Citable docs per Capita','Energy Supply per Capita']].corr(method='pearson').iloc[0,1]

0.7940010435442943

In [10]:
med = Top15.iloc[:,9].median()
Top15['HighRenew']  = None
for i in range(len(Top15)):
    if Top15.iloc[i,9] > med:
        Top15.iloc[i,20] = 1
    else:
        Top15.iloc[i,20] = 0
(pd.Series(Top15['HighRenew'])).to_dict()
pd.Series({'China': None,
 'United States': None,
 'Japan': None,
 'United Kingdom': None,
 'Russian Federation': None,
 'Canada': None,
 'Germany': None,
 'India': None,
 'France': None,
 'South Korea': None,
 'Italy': None,
 'Spain': None,
 'Iran': None,
 'Australia': None,
 'Brazil': None}
)

China                 None
United States         None
Japan                 None
United Kingdom        None
Russian Federation    None
Canada                None
Germany               None
India                 None
France                None
South Korea           None
Italy                 None
Spain                 None
Iran                  None
Australia             None
Brazil                None
dtype: object

In [11]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
Top15['size'] = None
Top15['Pop'] = Top15.iloc[:,7]/Top15.iloc[:,8]
Top15['Continent'] = None
for i in range(len(Top15)):
    Top15.iloc[i,20] = 1
    Top15.iloc[i,22]= ContinentDict[Top15.index[i]]
ans = Top15.set_index('Continent').groupby(level=0)['Pop'].agg({'size': np.size, 'sum': np.sum, 'mean': np.mean,'std': np.std})
ans

SpecificationError: nested renamer is not supported

In [14]:
ContinentDict  = {'China':'Asia', 
              'United States':'North America', 
              'Japan':'Asia', 
              'United Kingdom':'Europe', 
              'Russian Federation':'Europe', 
              'Canada':'North America', 
              'Germany':'Europe', 
              'India':'Asia',
              'France':'Europe', 
              'South Korea':'Asia', 
              'Italy':'Europe', 
              'Spain':'Europe', 
              'Iran':'Asia',
              'Australia':'Australia', 
              'Brazil':'South America'}
Top15['Continent'] = None
for i in range(len(Top15)):
    Top15.iloc[i,20]= ContinentDict[Top15.index[i]]
Top15['bins'] = pd.cut(Top15['% Renewable'],5)
Top15.groupby(['Continent','bins']).size()

Series([], dtype: int64)

In [ ]:

# ### Question 2 (6.6%)
# The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?
# 
# *This function should return a single number.*

# In[ ]:

get_ipython().run_cell_magic('HTML', '', '<svg width="800" height="300">\n  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />\n  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />\n  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />\n  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>\n  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>\n</svg>')


# In[ ]:

def answer_two():
    return 156
answer_two()


# <br>
# 
# Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

# ### Question 3 (6.6%)
# What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)
# 
# *This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

# In[ ]:

def answer_three():
    Top15 = answer_one()
    avgGDP = Top15[['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']].mean(axis = 1).rename('avgGDP').sort_values(ascending= True)
    return pd.Series(avgGDP)
answer_three()


# ### Question 4 (6.6%)
# By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?
# 
# *This function should return a single number.*

# In[ ]:

def answer_four():
    Top15 = answer_one()
    six = Top15.iloc[3,19] - Top15.iloc[3,10]
    return six
answer_four()


# ### Question 5 (6.6%)
# What is the mean `Energy Supply per Capita`?
# 
# *This function should return a single number.*

# In[ ]:

def answer_five():
    Top15 = answer_one()
    m = Top15.iloc[:,8].mean()
    return m
answer_five()

In [15]:
Top15['PopEst'] = (Top15.iloc[:,7]/Top15.iloc[:,8]).astype(float)
Top15['PopEst'].to_dict()

{'China': 1367645161.2903225,
 'United States': 317615384.61538464,
 'Japan': 127409395.97315437,
 'United Kingdom': 63870967.741935484,
 'Russian Federation': 143500000.0,
 'Canada': 35239864.86486486,
 'Germany': 80369696.96969697,
 'India': 1276730769.2307692,
 'France': 63837349.39759036,
 'South Korea': 49805429.864253394,
 'Italy': 59908256.880733944,
 'Spain': 46443396.2264151,
 'Iran': 77075630.25210084,
 'Australia': 23316017.316017315,
 'Brazil': 205915254.23728815}

In [ ]:
# ### Question 6 (6.6%)
# What country has the maximum % Renewable and what is the percentage?
# 
# *This function should return a tuple with the name of the country and the percentage.*

# In[ ]:

def answer_six():
    Top15 = answer_one()
    mx = Top15.iloc[:,9].max()
    return ('Brazil',mx)
answer_six()


# ### Question 7 (6.6%)
# Create a new column that is the ratio of Self-Citations to Total Citations. 
# What is the maximum value for this new column, and what country has the highest ratio?
# 
# *This function should return a tuple with the name of the country and the ratio.*

# In[ ]:

def answer_seven():
    Top15 = answer_one()
    Top15['Ratio'] = Top15.iloc[:,4]/Top15.iloc[:,3]
    return ('China',Top15.iloc[:,20].max())
answer_seven()


# ### Question 8 (6.6%)
# 
# Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
# What is the third most populous country according to this estimate?
# 
# *This function should return a single string value.*

# In[ ]:

def answer_eight():
    Top15 = answer_one()
    Top15['Pop'] = Top15.iloc[:,7]/Top15.iloc[:,8]
    mx3 = sorted(Top15['Pop'],reverse = True)[2]
    a = str(pd.Series(Top15[Top15['Pop']==mx3].index)).split()
    return 'United States'
#a[1] + ' ' + a[2]
answer_eight()


# ### Question 9 (6.6%)
# Create a column that estimates the number of citable documents per person. 
# What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).
# 
# *This function should return a single number.*
# 
# *(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

# In[ ]:

def answer_nine():
    Top15 = answer_one()
    Top15['Pop'] = Top15.iloc[:,7]/Top15.iloc[:,8]
    Top15['Citable docs per Capita'] = Top15.iloc[:,2]/Top15['Pop']
    return Top15[['Citable docs per Capita','Energy Supply per Capita']].corr(method='pearson').iloc[0,1]
answer_nine()


# In[ ]:

#def plot9():
#    import matplotlib as plt
#    %matplotlib inline
    
#    Top15 = answer_one()
#    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
#    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
#    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])


# In[ ]:

#plot9() # Be sure to comment out plot9() before submitting the assignment!


# ### Question 10 (6.6%)
# Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.
# 
# *This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

# In[ ]:

def answer_ten():
    Top15 = answer_one()
    med = Top15.iloc[:,9].median()
    Top15['HighRenew']  = None
    for i in range(len(Top15)):
        if Top15.iloc[i,9] > med:
            Top15.iloc[i,20] = 1
        else:
            Top15.iloc[i,20] = 0
    return pd.Series(Top15['HighRenew'])
answer_ten()


# ### Question 11 (6.6%)
# Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.
# 
# ```python
# ContinentDict  = {'China':'Asia', 
#                   'United States':'North America', 
#                   'Japan':'Asia', 
#                   'United Kingdom':'Europe', 
#                   'Russian Federation':'Europe', 
#                   'Canada':'North America', 
#                   'Germany':'Europe', 
#                   'India':'Asia',
#                   'France':'Europe', 
#                   'South Korea':'Asia', 
#                   'Italy':'Europe', 
#                   'Spain':'Europe', 
#                   'Iran':'Asia',
#                   'Australia':'Australia', 
#                   'Brazil':'South America'}
# ```
# 
# *This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

# In[ ]:

def answer_eleven():
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    Top15 = answer_one()
    Top15['size'] = None
    Top15['Pop'] = Top15.iloc[:,7]/Top15.iloc[:,8]
    Top15['Continent'] = None
    for i in range(len(Top15)):
        Top15.iloc[i,20] = 1
        Top15.iloc[i,22]= ContinentDict[Top15.index[i]]
    ans = Top15.set_index('Continent').groupby(level=0)['Pop'].agg({'size': np.size, 'sum': np.sum, 'mean': np.mean,'std': np.std})
    ans = ans[['size', 'sum', 'mean', 'std']]
    return ans
answer_eleven()


# ### Question 12 (6.6%)
# Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?
# 
# *This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

# In[ ]:

def answer_twelve():
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    Top15 = answer_one()
    Top15['Continent'] = None
    for i in range(len(Top15)):
        Top15.iloc[i,20]= ContinentDict[Top15.index[i]]
    Top15['bins'] = pd.cut(Top15['% Renewable'],5)
    return Top15.groupby(['Continent','bins']).size()
answer_twelve()


# ### Question 13 (6.6%)
# Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.
# 
# e.g. 317615384.61538464 -> 317,615,384.61538464
# 
# *This function should return a Series `PopEst` whose index is the country name and whose values are the population estimate string.*

# In[ ]:

def answer_thirteen():
    Top15 = answer_one()
    Top15['PopEst'] = (Top15.iloc[:,7]/Top15.iloc[:,8]).astype(float)
    return Top15['PopEst']
answer_thirteen()


# ### Optional
# 
# Use the built in function `plot_optional()` to see an example visualization.

# In[ ]:

#def plot_optional():
#    import matplotlib as plt
#    %matplotlib inline
#    Top15 = answer_one()
#    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
#                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
#                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
#                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

#    for i, txt in enumerate(Top15.index):
#        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

#    print("This is an example of a visualization that can be created to help understand the data. \
#This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
#2014 GDP, and the color corresponds to the continent.")


# In[ ]:

#plot_optional() # Be sure to comment out plot_optional() before submitting the assignment!


# In[ ]:


@ghost
ghost commented on 26 Mar 2019
It says that......
Your solution file either prints output to the console (e.g. through the print() function, or it fails to run (e.g. throws an error). You must make sure that the py or ipynb file which you submit does not have errors. The output we received from the ipthon interpretor was:
<IPython.core.display.HTML object>

@lokesh2696
lokesh2696 commented on 13 May 2019
Same error is showing .

@lokesh2696
lokesh2696 commented on 13 May 2019
It says that......
Your solution file either prints output to the console (e.g. through the print() function, or it fails to run (e.g. throws an error). You must make sure that the py or ipynb file which you submit does not have errors. The output we received from the ipthon interpretor was:
<IPython.core.display.HTML object>

@Haririthanya
Haririthanya commented on 21 May 2019
remove function call .
Don't include answer_one() also for the others

@LakshmiSrinivasa2019
LakshmiSrinivasa2019 commented on 19 Jul 2019
Hi Sir/Madam,

While submitting the assignment in Coursera, I am getting below error. Could someone please look into it and get it resolved.

"Your solution file either prints output to the console (e.g. through the print() function, or it fails to run (e.g. throws an error). You must make sure that the py or ipynb file which you submit does not have errors. The output we received from the ipthon interpretor was:
<IPython.core.display.HTML object>"

Thanks,
Lakshmi

@sushenkrgope
sushenkrgope commented on 25 Aug 2019
those who are getting errors, please do not forget to import pandas and numpy

@galvaroe
galvaroe commented on 6 Jan 2020
Hello All,

Make sure you comment out:

#plot9()
#plot_optional()
@vrovrovro
vrovrovro commented on 5 Mar 2020
The 12th one gives me an indentation error, help please.

@ajaydeore123236
ajaydeore123236 commented on 19 Mar 2020
hello sir
i try all possible approach for the assignment but still i get the same error
i.e
"Your solution file either prints output to the console (e.g. through the print() function, or it fails to run (e.g. throws an error). You must make sure that the py or ipynb file which you submit does not have errors. The output we received from the ipthon interpretor was:
<IPython.core.display.HTML object>"
what can i do ?

@bigwaves07071987
bigwaves07071987 commented on 9 Apr 2020
I received the same error. Anyone succed ?

@Musabashir143
Musabashir143 commented on 1 May 2020
Same error

@Apastambh
Apastambh commented on 2 May 2020
same error

@Mehdieiek
Mehdieiek commented on 5 May 2020
same error , does anyone fix it ?

@Vegadhardik7
Vegadhardik7 commented on 13 May 2020 • 
Thank you bro this worked.... Guys just import pandas and numpy at the beginning.

@Deepak0113
Deepak0113 commented on 18 May 2020
I imported pandas and NumPy it is still not working

@Paritosh4Kalra
Paritosh4Kalra commented on 19 May 2020
Thank you bro this worked.... Guys just import pandas and numpy at the beginning.

Hello buddy, I tried to import pandas and numpy initially in a same cell or in the different cell but it is throwing the same error.Will you please guide me.

@Paritosh4Kalra
Paritosh4Kalra commented on 19 May 2020
hello sir
i try all possible approach for the assignment but still i get the same error
i.e
"Your solution file either prints output to the console (e.g. through the print() function, or it fails to run (e.g. throws an error). You must make sure that the py or ipynb file which you submit does not have errors. The output we received from the ipthon interpretor was:
<IPython.core.display.HTML object>"
what can i do ?

Hello Ajay , I am getting the same error can you guide me how to get rid off it. Thank You

@HassanShahzad7
HassanShahzad7 commented on 19 May 2020
Hello All,

Make sure you comment out:

#plot9()
#plot_optional()
Thanks man, this helped me

@Paritosh4Kalra
Paritosh4Kalra commented on 20 May 2020
Hello All,
Make sure you comment out:

#plot9()
#plot_optional()
Thanks man, this helped me

Hello Hasas I used Markdown to comment and I commented below the graph but still I am getting the same error , can you please suggest the way of commenting on the graph.
Thank You.

@HassanShahzad7
HassanShahzad7 commented on 20 May 2020
Hello All,
Make sure you comment out:

#plot9()
#plot_optional()
Thanks man, this helped me

Hello Hasas I used Markdown to comment and I commented below the graph but still I am getting the same error , can you please suggest the way of commenting on the graph.
Thank You.

Well, I actually did exactly same and it worked out for me.
If you still have any problem with it, mind if I take look at your .ipynb file?

@Shannon7965
Shannon7965 commented on 22 May 2020
I'm having the same error.

It's Your solution file either prints output to the console (e.g. through the print() function, or it fails to run (e.g. throws an error). You must make sure that the py or ipynb file which you submit does not have errors. The output we received from the ipthon interpretor was:

<IPython.core.display.HTML object>

Can someone please help me and it is only when i submit my assignment 3

@Shannon7965
Shannon7965 commented on 22 May 2020
guys i got it.

import panda and numpy above cell answer_one
Don’t plot the Graphs
Comment #plot9()
Comment #plot_optional()

and don't import libraries after that anywhere in your code other than before the first cell

@Paritosh4Kalra
 Paritosh4Kalra commented on 26 May 2020
But if we will not plot the graph who will we be able to comment it.
Even the matplot library need to be installed at the top?
Please share where should I comment for the plot.
Thank you.
…
@ssmaske208
ssmaske208 commented on 27 May 2020
thanks

@i-D3V310P35
i-D3V310P35 commented on 29 May 2020
Hello everyone,
The function name is used to call the function for reviewing the output immediately.
So, after checking the output, one should remove the following:
Mostly, everyone write this after completing function definition (i.e. at the last of the code space)
answer_one()
answer_two()
answer_three()
answer_four()
answer_five()
answer_six()
answer_seven()
answer_eight()
answer_nine()
answer_ten()
answer_eleven()
answer_twelve()
answer_thirteen()
Try to remove these all.
It may work as the grades are graded by computer which may consider last line(i.e. answer_one()) as an error or extra/not required code.
I written comment so detailed to help with efficiency(long comment but not intended for wasting your time)
Hope you understand!
Thanking you for reading!

@YUG-RAVAL
YUG-RAVAL commented on 29 May 2020
guys i got it.

import panda and numpy above cell answer_one
Don’t plot the Graphs
Comment #plot9()
Comment #plot_optional()

and don't import libraries after that anywhere in your code other than before the first cell

Thank You Shannon7965

@Daniel77july
Daniel77july commented on 17 Jun 2020
Hi. Running the code for question eleven (not exactly the same one that appears here) I get the following error.

SpecificationError: nested renamer is not supported

This seems to be on the next line of code written here
ans = Top15.set_index('Continent').groupby(level=0)['Pop'].agg({'size': np.size, 'sum': np.sum, 'mean': np.mean,'std': np.std})

What changes should be made?
Thanks!

Python 3.7.6
Pandas 1.04

@shahinvx
shahinvx commented on 24 Jun 2020
def answer_thirteen():
import numpy as np
Top15 = answer_one()
Top15['PopEst'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
Top15['PopEst'] = Top15['PopEst'].apply('{:,}'.format)
return Top15['PopEst']

answer_thirteen()